### ISSUE TITLE
Scrap Guava's EventBus and design a publish-subscribe style plugin system from the ground up

### ISSUE THREAD

**Issue by lare96** [lare96/luna#2]
then I can design it to fit my exact needs rather than trying to "cheap hack" the core functionality of the EventBus

**Comment by lare96** [comment]
I want it to be designed like so...

Plugin<T extends PluginContext>

- Base class for all plugins, all plugins must extend this class. will give access to the world, plugin manager, game service, and player as protected fields and will also have common methods to make development easier (like an inline schedule method for tasks, actions, etc). will also contain an abstract method describing what the plugin does

PluginEnvironment

- An annotation with a single argument of a class extending PluginContext

PluginEnvironmentException

- An exception detailing a Plugin with an invalid environment

PluginExecutionException

- An exception detailing a Plugin that throws an exception during execution

PluginPipeline<T extends PluginContext>

- A pipeline dedicated to a certain PluginContext, contains all of the Plugin's in the order they were added

PluginManager

- Maintains a map of PluginContext's to PluginPipeline's

**Comment by lare96** [comment]
Changing PluginEnvironment from annotation to an external file that allows for more data, and PluginEnvironmentException to PluginRegisterationException

**Comment by ryleykimmel** [comment]
Trying to remove the need for the annotation and external file would be a good move -- it's overly complex for 'drag-and-drop' like features (and a tad confusing for inexperienced users)

Rather than annotating to a specific 'event' or 'context' I would let event listeners/events in general be extended.

Plugins can then be organized into a multimap/pipeline like structure, going down the pipeline until the chain is broken (click door, door opens in one plugin, door also completes part of a quest in another plugin [tutorial island?], break chain)

**Comment by lare96** [comment]
I like that idea much better actually, of just having multiple "base listeners" that can be extended

**Comment by lare96** [comment]
Fixed in most recent commit
